# Generated by Django 4.2.17 on 2025-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_favourite_rename_games_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='favourite',
            name='game2',
            field=models.ManyToManyField(to='profiles.game'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='platform2',
            field=models.ManyToManyField(to='profiles.platform'),
        ),
    ]
