# Generated by Django 4.2.17 on 2025-01-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_favourite_game2_alter_favourite_platform2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='game2',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='platform2',
        ),
        migrations.RemoveField(
            model_name='library',
            name='game2',
        ),
        migrations.AlterField(
            model_name='favourite',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.game'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.platform'),
        ),
        migrations.RemoveField(
            model_name='library',
            name='game',
        ),
        migrations.RemoveField(
            model_name='library',
            name='platform',
        ),
        migrations.AddField(
            model_name='library',
            name='game',
            field=models.ManyToManyField(to='profiles.game'),
        ),
        migrations.AddField(
            model_name='library',
            name='platform',
            field=models.ManyToManyField(to='profiles.platform'),
        ),
    ]
