# Generated by Django 4.2.17 on 2025-01-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_privacy_user_profile_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacy',
            name='user',
        ),
        migrations.AddField(
            model_name='privacy',
            name='privacy',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='privacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Privacy', to='profiles.privacy'),
        ),
    ]
