# Generated by Django 4.2.17 on 2025-01-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_privacy_user_privacy_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='privacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_Privacy', to='profiles.privacy'),
        ),
    ]
