# Generated by Django 4.2.17 on 2025-01-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_user_profile_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_library',
            name='game',
        ),
        migrations.AddField(
            model_name='user_library',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profiles.game'),
            preserve_default=False,
        ),
    ]
