# Generated by Django 4.2.17 on 2025-01-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=True),
        ),
    ]
