# Generated by Django 4.2.17 on 2025-01-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_comment_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='comment',
        ),
    ]
