# Generated by Django 4.2.17 on 2025-01-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_rename_comment_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='privacy',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
