# Generated by Django 4.2.17 on 2025-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_privacy_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='privacy',
            field=models.CharField(max_length=50),
        ),
    ]
